In [1]:
#beginning of numpy 

In [2]:
# !pip install numpy

In [1]:
import numpy as np
print(np.__version__)


2.3.2


In [4]:
l1=[1,2,3,4]
l2=[[1,2], [3,4], [5,6]]
l3=[[[10,20],[30,40]],[[1,2],[3,4]]]

In [5]:
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.array(l3)


In [6]:
#numpy array is homogeneous b/c numpy code is c and cpp

In [7]:
#multiplication in python list and array(numpy array)
py_list=[1,2,3]
print("python list multiplication", py_list*2)

py_array=np.array(py_list)
print("python array multiplication", py_array*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


In [8]:
#time taken by list ans numpy array
import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("list operation time: ", time.time()-start)

start=time.time()
np_array=np.arange(100000)
print("numpy operation time: ", time.time()-start)

list operation time:  0.011677026748657227
numpy operation time:  0.0


In [9]:
#creating different types of matrices
zeros=np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
full=np.full((3,4),5)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
random=np.random.random((3,4))
random

array([[0.56952134, 0.45073516, 0.74507911, 0.62769212],
       [0.64095297, 0.08236668, 0.44620746, 0.9297072 ],
       [0.14541094, 0.51419314, 0.54674201, 0.84830649]])

In [13]:
sequence=np.arange(0,100,5)
sequence

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
### array properties
#shape, ndim, size, dtype

arr=np.array([[1,2,3],[4,5,6]])
print("shape: ", arr.shape)
print("dimensional: ", arr.ndim)
print("size: ", arr.size)
print("dtype: ", arr.dtype)

shape:  (2, 3)
dimensional:  2
size:  6
dtype:  int64


In [17]:
#phase-2
#basic slicing and indexing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing: ", arr[2:7])
print("basic slicing: ", arr[2:7:2])


basic slicing:  [3 4 5 6 7]
basic slicing:  [3 5 7]


In [19]:
#2d-array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element", arr_2d[1,2]) #element at 2nd row and 3rd column
print("entire row", arr_2d[1]) # 2nd row entire
print("entire column", arr_2d[:,1])#2nd colmn entire

specific element 6
entire row [4 5 6]
entire column [2 5 8]


In [21]:
#sorting
unsorted=np.array([3,1,5,4,2,1,3,2])
np.sort(unsorted)

array([1, 1, 2, 2, 3, 3, 4, 5])

In [23]:
arr_2d_unsorted=np.array([[2,3],[1,2],[3,1]])
print("sorted 2d array by column",np.sort(arr_2d_unsorted, axis=0)) #sorted in each column (top to bottom)
print("sorted 2d array by row",np.sort(arr_2d_unsorted, axis=1)) #sorted in each row (left to right)

sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row [[2 3]
 [1 2]
 [1 3]]


In [25]:
#filters using expressions and mask
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers= numbers[numbers%2==0]  #filter by expression
even_numbers

array([ 2,  4,  6,  8, 10])

In [26]:
#filtering by mask
mask=numbers>5
numbers[mask]

array([ 6,  7,  8,  9, 10])

In [30]:
#fancy indexing and np.where()
indices = [0,2,4]
print(numbers[indices])

where_result= np.where(numbers>5)#kinda type of masking
print(where_result)#stores indices satisfy the masking condition
numbers[where_result]

[1 3 5]
(array([5, 6, 7, 8, 9]),)


array([ 6,  7,  8,  9, 10])

In [32]:
#combnation of arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1, arr2))
combined

array([1, 2, 3, 4, 5, 6])

In [34]:
#compatibility of arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("compatibility checking before making 2-d array \n", a.shape==b.shape)

compatibility checking before making 2-d array 
 True


In [40]:
#adding a row in array matrix (psuhback a row in 2d vector)
old_arr=np.array([[1,2],[3,4]])
new_arr=np.array([5,6])
stack_new_row=np.vstack((old_arr, new_arr))
stack_new_arr

#adding new columns in array or matix
new_col=np.array([[7],[8]])
stack_new_col=np.hstack((old_arr,new_col))
stack_new_col

array([[1, 2, 7],
       [3, 4, 8]])

In [43]:
narr=np.arange(1,101)
narr=narr.reshape((10,10))
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [44]:
narr[3:6,4:8]

array([[35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58]])

In [45]:
narr[3:6,4:8]=np.arange(1,13).reshape((3,4))
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   2,   3,   4,  39,  40],
       [ 41,  42,  43,  44,   5,   6,   7,   8,  49,  50],
       [ 51,  52,  53,  54,   9,  10,  11,  12,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [46]:
narr[4]=np.arange(1,11)

In [47]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   2,   3,   4,  39,  40],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 51,  52,  53,  54,   9,  10,  11,  12,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [50]:
barr=narr[8:10]
barr[:,1:3]=np.arange(1,5).reshape((2,2))#actually a view (not a copy) of last two rows of narr
barr

array([[ 81,   1,   2,  84,  85,  86,  87,  88,  89,  90],
       [ 91,   3,   4,  94,  95,  96,  97,  98,  99, 100]])

In [53]:
#vectorization (this is what numpy famous for)

import time

l=[i for i in range(10**7)]
start=time.time()
for i in range(len(l)):
    l[i]=l[i]+10
end=time.time()
print("time for python", end-start)

time for python 2.2519137859344482


In [54]:
narr=np.arange(10**7)
start=time.time()
narr=narr+10
end=time.time()
print("time for numpy", end-start)

time for numpy 0.04779839515686035


In [ ]:
#n1 = numpy array
#n1=n1-3  each element get subracted 
#n1=n1*3  each element multiplied
#n1>2     each element can be either true or false wrt this condition



In [55]:
n1=np.array([[1,2,3],[4,5,6]])
n2=np.array([[10,20,30],[40,50,60]])

In [56]:
n1+n2

array([[11, 22, 33],
       [44, 55, 66]])

In [57]:
n1*n2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [59]:
n1=np.arange(1,21)
np.random.shuffle(n1)
n1

array([ 3,  2, 10, 16, 13, 15,  5, 18, 17,  4, 11, 14, 20,  1,  6,  8, 12,
        7, 19,  9])

In [60]:
#n1[start:end:step-size]
n1[1::2]

array([ 2, 16, 15, 18,  4, 14,  1,  8,  7,  9])

In [61]:
#filtering elements based on index
n1[[2,4,9,15,18]]

array([10, 13,  4,  8, 19])

In [62]:
#important function

n1=np.array([2,5,4,1,3])
n2=np.array([10,20,30,40,50])

idx=np.argsort(n1)
n1=n1[idx]
n2=n2[idx]

print(n1,n2)

[1 2 3 4 5] [40 10 50 30 20]


In [63]:
n1=np.array([2,5,4,1,3])
n2=np.array([10,20,30,40,50])

idx=np.argsort(n1)[::-1]
n1=n1[idx]
n2=n2[idx]

print(n1,n2)

[5 4 3 2 1] [20 30 50 10 40]


In [78]:
#filtering and masking already finished 
narr=np.arange(1,101).reshape((10,10))
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [70]:
barr=narr[:,0]
barr=barr[(barr-1)%4==0]
barr


array([ 1, 21, 41, 61, 81])

In [74]:
#narr[(narr[:,0]-1)%4==0,0] // for column=0
#narr[(narr[:,0]-1)%4==0] // for rows
#narr[:, narr[0]%4==0]


#all those column in 1st row divisible by 4
narr=narr[0, narr[0]%4==0]


array([4, 8])

In [76]:
narr=narr[:, narr[0]%4==0] #for all rows
narr

array([[ 4,  8],
       [14, 18],
       [24, 28],
       [34, 38],
       [44, 48],
       [54, 58],
       [64, 68],
       [74, 78],
       [84, 88],
       [94, 98]])

In [77]:
n1=np.arange(1,21).reshape(5,4)
n1[n1>8]#returns 1d array

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
np.sum(narr)

np.int64(5050)

In [83]:
narr=np.arange(1,101).reshape((10,10))

In [84]:
np.sum(narr,axis=0)#every column sum

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [85]:
np.sum(narr, axis=1)#every row sum

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [ ]:
narr=narr.reshape(5,5,4)# 5 2d arrays me 5 rows and 4 columns


In [87]:
narr=np.arange(1,13).reshape(2,3,2)
narr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [88]:
np.sum(narr, axis=0)

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [89]:
np.sum(narr, axis=1)

array([[ 9, 12],
       [27, 30]])

In [90]:
np.sum(narr, axis=2) #equals to narr.sum(axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])

In [91]:
np.max(narr, axis=2)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [92]:
np.max(narr, axis=1)

array([[ 5,  6],
       [11, 12]])

In [95]:
np.max(narr[0], axis=0)

array([5, 6])

In [93]:
np.max(narr, axis=0)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [96]:
#argmax 
np.argmax(narr)

np.int64(11)