In [1]:
#covered numpy in 28_09, 10_04 and 10_05 
#matrix multiplixcation

In [3]:
import numpy as np
n1=np.arange(1,7).reshape(3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
n2=np.arange(1,7).reshape(2,3)
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
n1.dot(n2)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [9]:
n2.dot(n1)

array([[22, 28],
       [49, 64]])

In [10]:
n1@n2

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])