In [1]:
import numpy as np


In [2]:
n1=np.random.randint(1,100,30)
n1

array([72, 27, 95, 32, 75, 15, 52, 93, 38, 67,  8, 25, 86, 93, 50, 92, 54,
       22, 24, 17, 61, 11, 76, 17, 41,  8,  7, 26, 97, 34], dtype=int32)

In [10]:
#numbers between 10 and 30
n1=n1[(n1>10)]
n1[(n1<30)]

array([27, 15, 25, 22, 24, 17, 11, 17, 26], dtype=int32)

In [12]:
#we cant use "and" here
n1[(n1>=10) & (n1<=30)]
n1[(n1>=10) * (n1<=30)]

array([27, 15, 25, 22, 24, 17, 11, 17, 26], dtype=int32)

In [14]:
narr=np.arange(1,13).reshape((2,3,2))
narr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [25]:
for i in range(0,2):
    for j in range(0,3):
        for k in range(0,2):
            print(narr[i][j][k], end=" ")
        print()

1 2 
3 4 
5 6 
7 8 
9 10 
11 12 


In [26]:
narr.shape

for i in range(narr.shape[0]):
    for j in range(narr.shape[1]):
        for k in range(narr.shape[2]):
            print(narr[i,j,k], end=" ")#best way to waccess indices in mumpy
        print() 

1 2 
3 4 
5 6 
7 8 
9 10 
11 12 


In [30]:
for t in np.nditer(narr):
    print(t,end=" ")
    

1 2 3 4 5 6 7 8 9 10 11 12 

In [32]:
for t in np.ndenumerate(narr):
    print(t)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(4))
((0, 2, 0), np.int64(5))
((0, 2, 1), np.int64(6))
((1, 0, 0), np.int64(7))
((1, 0, 1), np.int64(8))
((1, 1, 0), np.int64(9))
((1, 1, 1), np.int64(10))
((1, 2, 0), np.int64(11))
((1, 2, 1), np.int64(12))


In [34]:
n1=np.array([1,2,3])
n2=np.array([10,20,30])

In [36]:
#number of columns must be same
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [38]:
#number of rows must be same in n1 and n2
np.hstack((n1,n2))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
#np.concatenate (n1,n2 with axis=0,1...)
#np.stack (n1,n2 with axis=0,1..)
#np.hsplit


In [51]:
#broadcasting is the important concept
#use case if transpose

n1=np.arange(1,13).reshape(3,4)
print(n1)
n2=np.transpose(n1)
print(n2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [43]:
#1st case
np.array([[10,20,30,40]])+n1

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

In [45]:
n2=np.arange(1,13).reshape(4,3)
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
#2nd case
np.array([[10],[20],[30],[40]])+n2

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39],
       [50, 51, 52]])

In [47]:
np.array([[10],[20],[30],[40]])+n1

ValueError: operands could not be broadcast together with shapes (4,1) (3,4) 

In [49]:
#3rd case
np.array([[10,20,30,40]])+np.array([[10],[20],[30],[40]])

array([[20, 30, 40, 50],
       [30, 40, 50, 60],
       [40, 50, 60, 70],
       [50, 60, 70, 80]])

In [58]:
pop= np.loadtxt('populations.txt')
pop

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [67]:
#find max population for every year and whose population
print(np.max(pop, axis=1))
# Find the index of the maximum population in each column
max_indices_row = np.argmax(pop, axis=1)
max_indices_row

[48300. 48200. 70200. 77400. 59400. 41700. 38600. 42300. 44500. 42100.
 46000. 46800. 57000. 76600. 52300. 51100. 36700. 41800. 43300. 41300.
 47300.]


array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 3, 3, 3])

In [65]:
# Extract columns using slicing
years = pop[:, 0]
populations = pop[:, 1:]
print(years)
print(populations)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [70]:
#find the years for these 3 categories maximum population
max_indices_col=np.argmax(populations, axis=0)
print(max_indices_col)

[3 4 0]


In [73]:
max_years_categories=years[max_indices_col]
print(max_years_categories)

[1903. 1904. 1900.]


In [74]:
#3rd problem- get me mean population of every year and every category
#mean population of every year
np.mean(populations, axis=1)

array([27433.33333333, 33833.33333333, 40500.        , 50266.66666667,
       45433.33333333, 34033.33333333, 25233.33333333, 25566.66666667,
       24933.33333333, 25533.33333333, 26833.33333333, 31700.        ,
       37700.        , 45666.66666667, 45800.        , 36533.33333333,
       25866.66666667, 21733.33333333, 22533.33333333, 22533.33333333,
       26866.66666667])

In [76]:
#mean population of every category
np.mean(populations, axis=0)
#other way
#np.mean(pop[:,1:], axis=0) -> extracting just population columns and filtering out year col(we dont need it)

array([34080.95238095, 20166.66666667, 42400.        ])

In [77]:
#by sir

In [79]:
np.max(pop[:,1:], axis=1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [80]:
categories= np.array(['year', 'hare', 'lynx','carrot'])
cat= np.argmax(pop[:,1:], axis=1)+1 #indexing incremented by 1
categories[cat]


array(['carrot', 'carrot', 'hare', 'hare', 'lynx', 'lynx', 'carrot',
       'carrot', 'carrot', 'carrot', 'carrot', 'carrot', 'hare', 'hare',
       'hare', 'lynx', 'carrot', 'carrot', 'carrot', 'carrot', 'carrot'],
      dtype='<U6')

In [81]:
pop[:,1:]

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [82]:
pop[np.argmax(pop[:,1:], axis=0)]

array([[ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1900., 30000.,  4000., 48300.]])