In [1]:
import numpy as np

In [4]:
def convolve(image, kernel):
    #get dimension of image and kernel
    image_h, image_w=image.shape
    kernel_h, kernel_w=kernel.shape

    #calculate padding
    pad_h, pad_w= kernel_h//2, kernel_w//2

    #created image after applying padding
    padding_image= np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant')

    #Initialize output
    output = np.zeros_like(image, dtype=np.float32)
    # output = np.zeros(image.shape, dtype=np.float32)

    for i in range(image_h):
        for j in range(image_w):

            roi=padding_image[i:i+kernel_h,j:j+kernel_w]

            output[i,j]=np.sum(roi*kernel)
    return output

image=np.array([[1,2,3],[4,5,6],[7,8,9]])
kernel=np.array([[1,1,1],[1,1,1],[1,1,1]])

print(convolve(image,kernel))
    

[[12. 21. 16.]
 [27. 45. 33.]
 [24. 39. 28.]]
